TRUNCATE TABLE player_character;
TRUNCATE TABLE alignment;
TRUNCATE TABLE proficiency;
TRUNCATE TABLE proficiency_type;
TRUNCATE TABLE attribute;
TRUNCATE TABLE language;
TRUNCATE TABLE background;
TRUNCATE TABLE class;
TRUNCATE TABLE race;
